#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$PASSWORD" != "null" ]]; then
  USE_PASSWORD="-W";
fi;

if [[ "$VANILLA" != "true" ]]; then
  export EDITOR=$QSH_SCRIPTS/qsh
  export PAGER=$QSH_SCRIPTS/qsh-pager

  QSH_PROMPT="\"--set=PROMPT1=$(cat $QSH_CLIENTS/psql/qsh-prompt)\""
fi;

if [[ "$PROMPT" != "true" ]]; then
  unset QSH_PROMPT;
fi;

QSH_INVOCATION="$CLIENT $INVOCATION $USE_PASSWORD $QSH_PROMPT";
PASSWORD_PROMPT="Password: ";

