#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$PASSWORD" != "null" ]]; then
  USE_PASSWORD="-p";
fi;

QSH_EDITOR=EDITOR=$QSH_SCRIPTS/qsh
QSH_PROMPT="--prompt='$(cat $QSH_CLIENTS/mysql/qsh-prompt)'"
QSH_PAGER="--pager=$QSH_SCRIPTS/qsh-pager"

if [[ "$PROMPT" == "false" ]]; then
  unset QSH_PROMPT;
fi;

if [[ "$VANILLA" == "true" ]]; then
  unset QSH_EDITOR QSH_PROMPT QSH_PAGER;
fi;

QSH_INVOCATION="$QSH_EDITOR '$CLIENT' $INVOCATION $USE_PASSWORD $QSH_PAGER $QSH_PROMPT";
PASSWORD_PROMPT="Enter password: ";

