#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$PASSWORD" != "null" ]]; then
  USE_PASSWORD="-p";
fi;

QSH_INVOCATION="EDITOR=$QSH_SCRIPTS/qsh '$CLIENT' $INVOCATION $USE_PASSWORD --pager=$QSH_SCRIPTS/qsh-pager --prompt='$(cat $QSH_CLIENTS/mysql/qsh-prompt)'";
PASSWORD_PROMPT="Enter password: ";

