#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$USING_PASSWORD" == "true" ]]; then
  LOGIN_PATH=--login-path=qsh
fi;

if [[ "$VANILLA" != "true" ]]; then
  export EDITOR=$QSH_SCRIPTS/qsh

  QSH_PROMPT="\"--prompt=$(cat $QSH_CLIENTS/mysql/qsh-prompt)\"";
  QSH_PAGER="--pager=$QSH_SCRIPTS/qsh-pager"
fi;

if [[ "$PROMPT" != "true" ]]; then
  unset QSH_PROMPT;
fi;

if [[ -f "$CONNECTION_FILE" ]]; then
  CONNECTION=$(basename "$CONNECTION_FILE");
  CLIENT_CONNECTION_FILE=$QSH_CONNECTIONS/.${CONNECTION}.reg

  eval "MYSQL_TEST_LOGIN_FILE='$CLIENT_CONNECTION_FILE' $CLIENT $LOGIN_PATH $INVOCATION $QSH_PAGER $QSH_PROMPT";
else
  eval "$CLIENT $INVOCATION $USE_PASSWORD $QSH_PAGER $QSH_PROMPT";
fi;

