#!/bin/bash

QSH_BASE=~/.qsh
QSH_CONNECTIONS=$QSH_BASE/connections

CONNECTION_FILE=$1
PASSWORD=$2

CONNECTION=$(basename "$CONNECTION_FILE");
CLIENT_CONNECTION_FILE=$QSH_CONNECTIONS/.${CONNECTION}.reg
export MYSQL_TEST_LOGIN_FILE=$CLIENT_CONNECTION_FILE

function set_mysql_config {
  read -r -d '' MYSQL_CONFIG_SETTER <<EOF
    set timeout -1
    log_user 0
    spawn mysql_config_editor set --login-path=qsh -p
    match_max 100000
    expect -exact "Enter password: "
    send -- "$PASSWORD\r"
    interact { -o eof {exit} }
EOF

  expect -c "$MYSQL_CONFIG_SETTER";
}

set_mysql_config;

