#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$VANILLA" != "true" ]]; then
  export RLWRAP_EDITOR=$QSH_SCRIPTS/qsh

  if [[ -z "$QSH_PAGER" ]]; then
    if [[ ! -z "$REPL_MODE" ]]; then
      export QSH_PAGER=cat
    fi;
  fi;
fi;

if [[ -f "$CONNECTION_FILE" ]]; then
  eval "QSH_CONNECTION=\"$CONNECTION\" QSH_FILE_TYPE=\"$FILE_TYPE\" $QSH_SCRIPTS/rlwrap.sh $CLIENT $INVOCATION";
else
  eval "QSH_INVOCATION=\"$INVOCATION\" QSH_FILE_TYPE=\"$FILE_TYPE\" $QSH_SCRIPTS/rlwrap.sh $CLIENT $INVOCATION";
fi;

