#!/bin/bash

cat <<EOF > $1
select s.name as TABLE_SCHEMA, t.name as TABLE_NAME, 'BASE TABLE' as TABLE_TYPE, coalesce(c.remark, '') as TABLE_COMMENT
from sys.tables t
inner join sys.schemas s on t.schema_id = s.id
left outer join sys.comments c on t.id = c.id
where query is null
order by 1, 2;
EOF

