#!/bin/bash

cat <<EOF > $1
select distinct s.name as ROUTINE_SCHEMA, f.name as ROUTINE_NAME, ft.function_type_keyword as ROUTINE_TYPE,
       fl.language_name as ROUTINE_BODY
from sys.functions f
inner join sys.schemas s on f.schema_id = s.id
inner join sys.function_types ft on f.type = ft.function_type_id
inner join sys.function_languages fl on f.language = fl.language_id
where f.system = false
order by 1, 2;
EOF

