#!/bin/bash

RESULT_REQUEST=$1
QUERY_FILE=$2
TRIGGER=$3

RESULT_REQUEST_STAGE_ONE="${RESULT_REQUEST}.stage1";
RESULT_REQUEST_OUTPUT="${RESULT_REQUEST}.output";
RESULT_REQUEST_FINALIZED="${RESULT_REQUEST}.finalized";

if [[ ! -f "$RESULT_REQUEST_STAGE_ONE" ]]; then
  # Trim leading & trailing whitespace
  TRIGGER="$(echo "$TRIGGER" | sed 's/^[[:space:]]\+//g; s/[[:space:]]\+$//g')";
  if [[ ! "$TRIGGER" =~ "." ]]; then
    TRIGGER=dbo.$TRIGGER
  fi;

  cat <<EOF > $QUERY_FILE
select object_definition(object_id('$TRIGGER'));
EOF

  # Only remove trailing spaces
  echo "TRAILING_SPACE" > "$RESULT_REQUEST";
  
  # Record that we have completed Stage 1
  touch "$RESULT_REQUEST_STAGE_ONE";
else
  if [[ -f "$RESULT_REQUEST_OUTPUT" ]]; then
    sed 's/^[[:space:]]//g; s/[[:space:]]*[+]$//g' "$RESULT_REQUEST_OUTPUT" \
      > "$RESULT_REQUEST_STAGE_ONE";

    # Put the results into the output file
    cat "$RESULT_REQUEST_STAGE_ONE" > "$RESULT_REQUEST_OUTPUT";
  fi;

  # We are done
  touch "$RESULT_REQUEST_FINALIZED";  
fi;

