#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select user as TABLE_SCHEMA, tc.TABLE_NAME,
         (case when tc.TABLE_TYPE = 'TABLE' then 'BASE TABLE' else 'VIEW' end) as TABLE_TYPE,
         t.NUM_ROWS as TABLE_ROWS,
         tc.COMMENTS as TABLE_COMMENT
  from USER_TAB_COMMENTS tc
  inner join USER_TABLES t on tc.TABLE_NAME = t.TABLE_NAME
  where TABLE_TYPE = 'TABLE'
  order by 1, 2
) t
$QUERY_CUSTOMIZATION;
EOF

