#!/bin/bash

QSH_CLIENTS=$QSH_BASE/clients

if [[ -z "$QSH_SQLCL_DISABLE_RESULT_PREPROCESSING" ]]; then
  export QSH_OUTPUT_FINALIZER=$QSH_CLIENTS/sqlcl/qsh-output-finalizer.pl;
  export QSH_RLWRAP_PAGER_CHECK=$QSH_CLIENTS/sqlcl/QshPagerCheck.pm;
fi;

# Update the invocation
INVOCATION="$INVOCATION @$QSH_CLIENTS/sqlcl/connect.sql";

# Other setting(s)
export QSH_RLWRAP_DISABLE_INITIALIZATION_MESSAGE=1

source $QSH_CLIENTS/generic/qsh-connect;

