#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select top 100 percent spid as process_id, db_name(dbid) as database_name, loginame as user_name, 
         (select client_net_address
          from sys.dm_exec_connections
          where session_id = t.spid) as user_address,
         program_name as application_name, login_time as session_start_timestamp,
         status as state, cmd as wait_type, lastwaittype as wait_event, 
         blocked
  from master.dbo.sysprocesses t
  where spid = @@spid
  order by 1
) t
$QUERY_CUSTOMIZATION;
EOF

