#!/bin/bash

QUERY_CUSTOMIZATION=$2

CUSTOMIZED_ORDER_BY=$(echo "$QUERY_CUSTOMIZATION" | grep -q "order by");
if [[ $? -ne 0 ]]; then
  ORDER_BY="order by 1, 2, 3"
fi;

cat <<EOF > $1
select * from (
  select TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
  from INFORMATION_SCHEMA.TABLES
  where TABLE_CATALOG = db_name()
  and TABLE_SCHEMA not in ('INFORMATION_SCHEMA', 'sys', 'guest')
  and TABLE_TYPE = 'BASE TABLE'
) t
$QUERY_CUSTOMIZATION
$ORDER_BY;
EOF

