#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select top 100 percent TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
  from INFORMATION_SCHEMA.TABLES
  where TABLE_CATALOG = db_name()
  and TABLE_TYPE = 'VIEW'
  order by 1, 2, 3
) t
$QUERY_CUSTOMIZATION;
EOF

