#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$VANILLA" != "true" ]]; then
  export VISUAL=$QSH_SCRIPTS/qsh

  QSH_PAGER="--pager=$QSH_SCRIPTS/qsh-pager"
fi;

if [[ -f "$CONNECTION_FILE" ]]; then
  CONNECTION=$(basename "$CONNECTION_FILE");
  CLIENT_CONNECTION_FILE=$QSH_CONNECTIONS/.${CONNECTION}.reg
  export DOTMONETDBFILE=$CLIENT_CONNECTION_FILE

  INVOCATION="$(echo "$INVOCATION" | sed 's/\(.*\) -u.*/\1/g')";
fi;

eval "$CLIENT $INVOCATION --width=-1 $QSH_PAGER";

