#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$VANILLA" != "true" ]]; then
  export VISUAL=$QSH_SCRIPTS/qsh
  export DOTMONETDB_FILE=

  QSH_PAGER="--pager=$QSH_SCRIPTS/qsh-pager"
fi;

QSH_INVOCATION="$CLIENT $INVOCATION --width=-1 $QSH_PAGER";
PASSWORD_PROMPT="password:";

