#!/bin/bash

QSH_BASE=~/.qsh
QSH_CONNECTIONS=$QSH_BASE/connections

CONNECTION_FILE=$1
PASSWORD=$2

CONNECTION=$(basename "$CONNECTION_FILE");
CLIENT_CONNECTION_FILE=$QSH_CONNECTIONS/.${CONNECTION}.reg

USER=$(jq -r '.invocation' "$CONNECTION_FILE" \
  | sed 's/.* -u[ ]\?["]\?\([^ ]\+\)[ ]\?["]\?/\1/g');

cat <<EOF > "$CLIENT_CONNECTION_FILE"
user=$USER
password=$PASSWORD
EOF

chmod 0600 "$CLIENT_CONNECTION_FILE";

