#!/bin/bash

QSH_SCRIPTS=$QSH_BASE/scripts
QSH_CLIENTS=$QSH_BASE/clients

if [[ "$VANILLA" != "true" ]]; then
  export VISUAL=$QSH_SCRIPTS/qsh

  QSH_PAGER="--pager=$QSH_SCRIPTS/qsh-pager"
fi;

if [[ -f "$CONNECTION_FILE" ]]; then
  export DOTMONETDBFILE=$CLIENT_CONNECTION_FILE

  INVOCATION="$(echo "$INVOCATION" | sed 's/\(.*\) -u.*/\1/g')";
fi;

