#!/bin/bash

cat <<EOF > $1
select TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
from INFORMATION_SCHEMA.TABLES
where table_schema not in ('pg_catalog', 'information_schema')
order by 1, 2, 3;
EOF

