#!/bin/bash

cat <<EOF > $1
select TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE,
       obj_description(concat(TABLE_SCHEMA, '.', TABLE_NAME)::regclass::oid) as TABLE_COMMENT
from INFORMATION_SCHEMA.TABLES
where TABLE_TYPE = 'BASE TABLE'
order by 1, 2, 3;
EOF

