#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select routine_schema, routine_name, routine_type, routine_body
  from information_schema.routines
  where routine_schema != 'information_schema'
  and routine_schema not like 'pg\_%'
  and routine_type = 'FUNCTION'
  order by 1, 2
) t
$QUERY_CUSTOMIZATION;
EOF

