#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select trigger_schema, trigger_name, event_manipulation, event_object_schema, event_object_table,
         action_order, action_orientation, action_timing
  from information_schema.triggers
  where trigger_schema != 'information_schema'
  and trigger_schema not like 'pg\_%'
  order by 1, 2
) t
$QUERY_CUSTOMIZATION;
EOF

