#!/bin/bash

cat <<EOF > $1
select s.name as TRIGGER_SCHEMA, t.name as TRIGGER_TABLE, tr.name as TRIGGER_NAME
from sys.triggers tr
inner join sys.tables t on tr.table_id = t.id
inner join sys.schemas s on t.schema_id = s.id
order by 1, 2, 3;
EOF

