#!/bin/bash

QSH_CLIENTS=$QSH_BASE/clients

if [[ -z "$QSH_SQLCMD_DISABLE_RESULT_PREPROCESSING" ]]; then
  export QSH_PAGER_PREPROCESSOR=$QSH_CLIENTS/sqlcmd/qsh-result-preprocessor.pl;
  INVOCATION="$INVOCATION -s ''\|''"
fi;

source $QSH_CLIENTS/generic/qsh-connect;

