#!/bin/bash

QSH_CLIENTS=$QSH_BASE/clients

if [[ -z "$QSH_SQLCMD_DISABLE_RESULT_PREPROCESSING" ]]; then
  export QSH_OUTPUT_FINALIZER=$QSH_CLIENTS/sqlcmd/qsh-output-finalizer.pl;
  INVOCATION="$INVOCATION -s ''\|''"
fi;

# Other setting(s)
export QSH_RLWRAP_DISABLE_INITIALIZATION_MESSAGE=1

source $QSH_CLIENTS/generic/qsh-connect;

