#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select s.name as TRIGGER_SCHEMA, tr.name as TRIGGER_NAME, 
         (case tr.event
              when 0 then 'INSERT'
              when 1 then 'DELETE'
              when 2 then 'UPDATE' end) as EVENT_MANIPULATION,
         s.name as EVENT_OBJECT_SCHEMA,
         t.name as EVENT_OBJECT_TABLE,
         row_number() over (partition by tr.table_id order by tr.id) as ACTION_ORDER,
         (case tr.orientation
              when 0 then 'ROW'
              when 1 then 'STATEMENT' end) as ACTION_ORIENTATION,
         (case tr.time
              when 0 then 'BEFORE'
              when 1 then 'AFTER'
              when 2 then 'INSTEAD OF' end) as ACTION_TIMING
  from sys.triggers tr
  inner join sys.tables t on tr.table_id = t.id
  inner join sys.schemas s on t.schema_id = s.id
  order by 1, 2
) t
$QUERY_OPTIMIZATION;
EOF

