#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select s.name as VIEW_SCHEMA, t.name as VIEW_NAME
  from sys.tables t
  inner join sys.schemas s on t.schema_id = s.id
  where query is not null
  order by 1, 2
) t
$QUERY_CUSTOMIZATION;
EOF

