#!/bin/bash

TABLE=$(cat $1)

cat <<EOF > $1
select group_concat(name, ', ') as columns
from (
  select c.name
  from sys.columns c
  inner join sys.tables t on c.table_id = t.id
  inner join sys.schemas s on t.schema_id = s.id
  where (
    charindex('.', '$TABLE', 0) <> 0 and
    s.name = replace(substr('$TABLE', 0, charindex('.', '$TABLE', 0) - 1), '"', '') and
    t.name = replace(substr('$TABLE', charindex('.', '$TABLE', 0) + 1), '"', '')
  ) or (
    charindex('.', '$TABLE', 0) = 0 and
    t.id = (select max(id) from sys.tables where name = replace('$TABLE', '"', ''))
  )
  order by number
) t;
EOF

