#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select (case when query is null then 'BASE TABLE' else 'VIEW' end) as TABLE_TYPE,
         s.name as TABLE_SCHEMA, t.name as TABLE_NAME, c.name as COLUMN_NAME, c.number + 1 as ORDINAL_POSITION,
         "default" as COLUMN_DEFAULT,
         (case when "null" then 'YES' else 'NO' end) as IS_NULLABLE, c.type as DATA_TYPE,
         (case when c.type in ('char', 'varchar') then type_digits else null end) as CHARACTER_MAXIMUM_LENGTH,
         (case when c.type not in ('char', 'varchar') then type_digits else null end) as NUMERIC_PRECISION,
         (case when c.type not in ('char', 'varchar') then type_scale else null end) as NUMERIC_SCALE
  from sys.columns c
  inner join sys.tables t on c.table_id = t.id
  inner join sys.schemas s on t.schema_id = s.id
  left outer join sys.comments co on c.id = co.id
  where not t.system
  order by 2, 3, 5
) t
$QUERY_CUSTOMIZATION;
EOF

