#!/bin/bash

QUERY_CUSTOMIZATION=$2

cat <<EOF > $1
select * from (
  select fs.name as REFERENCING_SCHEMA_NAME, ft.name as REFERENCING_TABLE_NAME, fk_name as REFERENCING_CONSTRAINT_NAME,
         s.name as REFERENCED_SCHEMA_NAME, t.name as REFERENCED_TABLE_NAME, key_name as REFERENCED_CONSTRAINT_NAME
  from dependency_keys_on_foreignkeys d
  inner join sys.tables t on d.key_table_id = t.id
  inner join sys.schemas s on t.schema_id = s.id
  inner join sys.tables ft on d.fk_table_id = ft.id
  inner join sys.schemas fs on ft.schema_id = fs.id
  where not s.system and not fs.system
  order by 1, 2, 3
) t
$QUERY_CUSTOMIZATION;
EOF

