#!/bin/bash

RESULT_REQUEST=$1
QUERY_FILE=$2
TABLE=$3

RESULT_REQUEST_FINALIZED="${RESULT_REQUEST}.finalized";
RESULT_REQUEST_OUTPUT="${RESULT_REQUEST}.output";

if [[ ! -f "$RESULT_REQUEST_OUTPUT" ]]; then
  # Trim leading & trailing whitespace
  TABLE="$(echo "$TABLE" | sed 's/^[[:space:]]\+//g; s/[[:space:]]\+$//g')";

  cat <<EOF > $QUERY_FILE
  select columns from (
    select sys.group_concat(c.name, ', ') over (order by number) as columns, number
    from sys.columns c
    inner join sys.tables t on c.table_id = t.id
    inner join sys.schemas s on t.schema_id = s.id
    where s.name =
      (case when locate('.', '$TABLE') = 0 then 'sys'
            else replace(replace(substr('$TABLE', 1, locate('.', '$TABLE') - 1), '\`', ''), '"', '')
       end)
    and t.name = 
      (case when locate('.', '$TABLE') = 0 then replace(replace('$TABLE', '\`', ''), '"', '')
            else replace(replace(substr('$TABLE', locate('.', '$TABLE') + 1), '\`', ''), '"', '')
       end)
    order by number desc
    limit 1
  ) t;
EOF
else
  # We are done
  touch "$RESULT_REQUEST_FINALIZED";  
fi;

