#!/bin/bash

QSH_SQLITE3="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
QSH_EXECUTE_QUERY=$1

# Perform generic finalization
$QSH_SQLITE3/../generic/qsh-input-finalizer "$QSH_EXECUTE_QUERY";

