#!/bin/bash

QSH_SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
QSH_PAGING_SCRIPTS=$QSH_SCRIPTS/paging

# The ID of the current pane, which should be the SQL client pane
PANE_ID=$(tmux display-message -p '#{pane_id}')

# Base directory for query editor tmp files
QSH_TMP=/tmp/qsh

# File that will exist if a result is requested, instead of displaying to the screen
RESULT_REQUEST=$QSH_TMP/client.${PANE_ID}.result-request
RESULT_REQUEST_OUTPUT="${RESULT_REQUEST}.output";
RESULT_REQUEST_COMPLETE="${RESULT_REQUEST}.complete";

# Optional input file, otherwise stdin will be used
INPUT_FILE=$1

# Optional processing args
shift;
PROCESSING_ARGS=$*

# The pager to be used display results
if [[ -z "$QSH_PAGER" ]]; then
  # No pager has been set, so try to find a suitable one
  QSH_PAGER="$(which pspg 2>/dev/null)";
  if [[ $? -ne 0 ]]; then
    # We couldn't find pspg, so use less (if we can)
    QSH_PAGER="$(which less 2>/dev/null)";
    if [[ $? -eq 0 ]]; then
      QSH_PAGER="$QSH_PAGER -SinFX";
    else
      # Default pager: just use cat
      QSH_PAGER="$(which cat)";
    fi;
  fi;
fi;

if [[ -f "$RESULT_REQUEST" ]] && [[ ! -f "$RESULT_REQUEST_OUTPUT" ]]; then
  # Create some file name we will use to communicate back to the QSH script
  RESULT_REQUEST_PERFORM_CLEANUP=$(cat "$RESULT_REQUEST");

  if [[ -z "$RESULT_REQUEST_PERFORM_CLEANUP" ]]; then
    # Cleanup the results and put them into the output file
    cat $INPUT_FILE \
        | $QSH_PAGING_SCRIPTS/standard-cleanup \
        | $QSH_PAGING_SCRIPTS/column-cleanup \
        | $QSH_PAGING_SCRIPTS/row-count-cleanup \
        | $QSH_PAGING_SCRIPTS/blank-lines-cleanup \
        > "$RESULT_REQUEST_OUTPUT";
  elif [[ "$RESULT_REQUEST_PERFORM_CLEANUP" == "TRAILING_SPACE" ]]; then
    # Cleanup the results and trailing space only
    cat $INPUT_FILE \
        | $QSH_PAGING_SCRIPTS/standard-cleanup \
        | $QSH_PAGING_SCRIPTS/trailing-cleanup \
        > "$RESULT_REQUEST_OUTPUT";
  elif [[ -f "$RESULT_REQUEST_PERFORM_CLEANUP" ]]; then
    # Used the specified file to cleanup the results
    cat $INPUT_FILE | "$RESULT_REQUEST_PERFORM_CLEANUP" $PROCESSING_ARGS > "$RESULT_REQUEST_OUTPUT";
  else
    # Don't cleanup the results, i.e. return them as is
    cat $INPUT_FILE > "$RESULT_REQUEST_OUTPUT";
  fi;
else
  if [[ ! -z "$QSH_OUTPUT_FINALIZER" ]]; then
    cat $INPUT_FILE | "$QSH_OUTPUT_FINALIZER" $PROCESSING_ARGS | $QSH_PAGER;
  else
    # No special processing: call the normal pager
    cat $INPUT_FILE | $QSH_PAGER;
  fi;
fi;

