#!/bin/bash

if [[ $# -eq 0 ]]; then
  echo;
  echo -e "\033[0;32mUsage\033[0m:";
  echo -e "  $ qsh [\033[0;33m-p\033[0m] <sql client invocation>";
  echo;
  echo -e "    \033[0;33m-p\033[0m\tA password is required to connect (optional)"
  echo;
  echo -e "\033[0;32mExamples\033[0m:";
  echo "  $ qsh -p mysql -uroot";
  echo "  $ qsh psql";
  echo;
  exit 0;
fi;

$*

