#!/bin/bash

# The pager to be used display results
if [[ -z "$QSH_PAGER" ]]; then
  # No pager has been set, so try to find a suitable one
  QSH_PAGER="$(which pspg 2>/dev/null)";
  if [[ $? -ne 0 ]]; then
    # We couldn't find pspg, so use less (if we can)
    QSH_PAGER="$(which less 2>/dev/null)";
    if [[ $? -eq 0 ]]; then
      QSH_PAGER="$QSH_PAGER -SinFX";
    else 
      # Default pager: just use cat
      QSH_PAGER="$(which cat)";
    fi;
  fi;
fi;

