#!/bin/bash

RESULT_REQUEST=$1
QUERY_FILE=$2
PROCEDURE=$3

RESULT_REQUEST_STAGE_ONE="${RESULT_REQUEST}.stage1";
RESULT_REQUEST_OUTPUT="${RESULT_REQUEST}.output";
RESULT_REQUEST_FINALIZED="${RESULT_REQUEST}.finalized";

if [[ ! -f "$RESULT_REQUEST_STAGE_ONE" ]]; then
  # Stage 1: request the script from the database

  # Trim leading & trailing whitespace
  PROCEDURE="$(echo "$PROCEDURE" | sed 's/^[[:space:]]\+//g; s/[[:space:]]\+$//g')";

  cat <<EOF > $QUERY_FILE
  show create procedure $PROCEDURE;
EOF

  # Only remove trailing spaces
  echo "TRAILING_SPACE" > "$RESULT_REQUEST";

  # Record that we have completed Stage 1
  touch "$RESULT_REQUEST_STAGE_ONE";
else
  # Stage 2: cleanup the output and return it
  echo "$(cat "$RESULT_REQUEST_OUTPUT" \
    | sed 's/^[^|]\+ | [^|]\+ | \(CREATE [^|]*\)/\1/g' \
    | sed 's/ | [^|]\+ | [^|]\+ | [^|]\+$//g; s/[[:space:]]$//g');" \
    > "$RESULT_REQUEST_STAGE_ONE";

  echo >> "$RESULT_REQUEST_STAGE_ONE";

  # Put the results into the output file
  cat "$RESULT_REQUEST_STAGE_ONE" > "$RESULT_REQUEST_OUTPUT";

  # We are done
  touch "$RESULT_REQUEST_FINALIZED";
fi;

