#!/bin/bash

FILTER=$2

cat <<EOF > $1
select * from (
  select TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE, 
         obj_description(concat(TABLE_SCHEMA, '.', TABLE_NAME)::regclass::oid) as TABLE_COMMENT
  from INFORMATION_SCHEMA.TABLES
  where TABLE_TYPE = 'VIEW'
) t
$FILTER
order by 1, 2, 3;
EOF

