#!/bin/bash

RESULT_REQUEST=$1
QUERY_FILE=$2
TABLE=$3

RESULT_REQUEST_FINALIZED="${RESULT_REQUEST}.finalized";
RESULT_REQUEST_OUTPUT="${RESULT_REQUEST}.output";

if [[ ! -f "$RESULT_REQUEST_OUTPUT" ]]; then
  # Trim leading & trailing whitespace
  TABLE="$(echo "$TABLE" | sed 's/^[[:space:]]\+//g; s/[[:space:]]\+$//g')";

  cat <<EOF > $QUERY_FILE
select listagg(COLUMN_NAME, ', ') within group(order by column_id) as columns
from ALL_TAB_COLUMNS
where OWNER =
  (case when instr('$TABLE', '.') != 0
        then upper(substr('$TABLE', 1, instr('$TABLE', '.') - 1))
        else user end)
and TABLE_NAME =
  (case when instr('$TABLE', '.') != 0
        then upper(substr('$TABLE', instr('$TABLE', '.') + 1))
        else upper('$TABLE') end);
EOF

  # Skip the first three lines of the output
  echo "3" > "$RESULT_REQUEST";
else
  # We are done
  touch "$RESULT_REQUEST_FINALIZED";  
fi;

